Bashbashbash patch 1
SIGBlockchain/aurum_client pull request #12
Opened 2019-09-10 18:48 UTC by bashbashbash

Updated for issue #2

2019-09-10 20:08 UTC, kastolars requested changes
I have added a checklist to the issue to show what is only needed.

2019-09-11 00:54 UTC, bashbashbash commented
updated

2019-09-12 05:44 UTC, kastolars requested changes

2019-09-12 05:44 UTC, kstola2 commented on README.md
> +sudo chmod +x setup.sh
I'm not sure these particular instructions will work for all OS's, perhaps specify that?

2019-09-12 05:44 UTC, kstola2 commented on README.md
> +A file called aurum_wallet.json was created. Copy this file and store it somewhere secure. __It contains your private key. If you lose you private key, you will lose access to your wallet and it is n
Urge the user to save a copy of `aurum_wallet.json` to another secure location just in case.

2019-09-12 05:44 UTC, kstola2 commented on README.md
> +Download this branch into your local environent.
Can we get a little more specific with what exactly to download? Perhaps just mention the zip folder and how to get the contents of it.

2019-09-21 17:35 UTC, kstola2 commented on README.md
> +sudo ./setup.sh
I don't think sudo runs on Windows

2019-09-21 17:36 UTC, kastolars requested changes

2019-09-21 17:36 UTC, kstola2 commented on README.md
> +Find the zip file you downloaded and unzip to your desired directoy.
For these binaries, can you simply add the link for the zip file?

2019-09-21 17:36 UTC, kstola2 commented on README.md
> +string means put the address of the person you want to interact with.
What about for the `send` flag?

2019-09-22 09:38 UTC, kastolars approved these changes

2019-09-23 20:18 UTC, merged