Proofreads the input
SIGBlockchain/aurum_client pull request #13
Opened 2019-09-11 22:30 UTC by ramirez915

proofreads input and exits if the input for the recipient is not 64 characters long

2019-09-12 05:41 UTC, kastolars requested changes
Can I request this proofreading be a function and have a supporting test? You can put it in the `wallet/` package.

2019-09-17 03:18 UTC, ramirez915 commented
Does the test look okay? I wasn't 100% sure on what else to test for this function

2019-09-17 17:19 UTC, kastolars requested changes

2019-09-17 17:19 UTC, kstola2 commented on internal/wallet/wallet.go
> +func ValidRecipLen(recipient string) (bool, error) {
- [ ] Remove the `error` return, I don't currently see a use for it.

2019-09-18 03:34 UTC, kastolars approved these changes

2019-09-18 13:39 UTC, merged